#!/bin/bash

# parse command line
cpuID=$1
server=$2

# globals
FIFO_P="/tmp/processor-${USER}-fifo-cpuID${cpuID}"
FIFO_DONE="/tmp/processor-${USER}-fifo"

function doJob {
  # execute the job
  $1 >> "/tmp/processor-$USER.${cpuID}.log"

  # report back to the server thats its done if the file exists
  if test -f "$FIFO_DONE"; then
    echo $cpuID > $FIFO_DONE
  fi

  
}

while read line < $FIFO_P; do
  if [ "$line" = 'exit' ]; then
      rm -f $FIFO_P
      exit 0
      break
  fi
    
  doJob $line
done
