#!/bin/bash

ID=$1
FIFO_P="/tmp/processor-${ID}-${USER}-fifo"
FIFO_P_STATUS="/tmp/processor-${ID}-status-${USER}-fifo"

#
# global variables
#

idle=0

#
# functions
#

function makeIdle {
  idle=0
}

function makeBusy {
  idle=1
}

function sendStatus {
  # output on the fifo to the server ONLY when signaled by the server
  echo $idle > FIFO_P_STATUS
}

function executeCommand {
  ./runProc $$ $1 &
}

function processInput {
  line=$1
  
  # set the processor to busy
  makeBusy

  # execute the line
  executeCommand "$line"
}

#
# traps
#

# this tells the processor it is done running a job
trap makeIdle SIGUSR2

# this is for sending the status to the server
trap sendStatus SIGUSR1

#
# main
#

# read every line from the fifo - sever will only send a line when idle
while read line < $FIFO_P
do
	if [ "$line" = 'exit' ]
	then
		break
	fi

	processInput "$line"
done
