#!/bin/bash

ID=$1
FIFO_P="/tmp/processor-${USER}-fifo"

#
# functions
#

function sendStatus {
  echo $ID
}

function executeCommand {
  # bash -c $1 >> processor-$USER.${ID}.log
  bash -c $1
}

function processInput {
  line=$1

  # execute the line
  executeCommand "$line"
}

#
# main
#

while read line < $FIFO_P
do
	if [ "$line" = 'exit' ]
	then
		break
	fi

	processInput "$line"
done
