#!/bin/bash

numCPU="$(getconf _NPROCESSORS_ONLN)"

# 32 timedCountdown test

echo "This test runs 32 timedCountdowns on the system"

./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown
./mgSubmit ./timedCountdown

./mgSubmit -s

echo "Wait for 32 / $numCPU * 10 seconds and then call ./mgSubmit -s"
echo "The status should say 32 jobs have been completed"

