#!/bin/sh

COUNT=5

if [ $# -gt 0 ]
then
    if ! [ $1 -eq $1 ] 2> /dev/null
    then
        echo "Argument must be an integer number of seconds" >&2
        exit 1
    fi
    COUNT=$1
fi

while [ $COUNT -gt 0 ]
do
    echo $COUNT
    sleep 1
    COUNT=$(( $COUNT - 1 ))
done

echo $COUNT

